[package]
name = "natural"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 's'
lto = false
codegen-units = 1

[dependencies]
bevy_egui = "0.30.0"
bevy = "0.14.2"
bevy_panorbit_camera = "0.19.3"

gpca = "0.1.3"
